name = "minesweeper-cloud"
compatibility_date = "2026-05-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "minesweeper-cloud"
database_id = "2c406393-ebf9-465c-9572-25f736f56c3c"
migrations_dir = "migrations"
